plugins {
    alias(libs.plugins.android.application)
    alias(libs.plugins.kotlin.android)
}

android {
    namespace 'com.mohamedaminelouati.calllimiterreminder'
    compileSdk 35

    defaultConfig {
        applicationId "com.mohamedaminelouati.calllimiterreminder"
        minSdk 24
        targetSdk 35
        versionCode 1
        versionName "1.0.0"

        testInstrumentationRunner "androidx.test.runner.AndroidJUnitRunner"
    }

    signingConfigs {
        release {
            if (file('calllimiter.jks').exists()) {
                storeFile file('calllimiter.jks')
                storePassword 'calllimiter123'
                keyAlias 'calllimiter'
                keyPassword 'calllimiter123'
                v1SigningEnabled true
                v2SigningEnabled true
            }
        }
    }

    dependenciesInfo {
        includeInApk = false
        includeInBundle = false
    }

    buildTypes {
        release {
            if (file('calllimiter.jks').exists()) {
                signingConfig signingConfigs.release
            }
            minifyEnabled false
            proguardFiles getDefaultProguardFile('proguard-android-optimize.txt'), 'proguard-rules.pro'
        }
        debug {
            if (file('calllimiter.jks').exists()) {
                signingConfig signingConfigs.release
            }
        }
    }
    compileOptions {
        sourceCompatibility JavaVersion.VERSION_17
        targetCompatibility JavaVersion.VERSION_17
    }
    kotlinOptions {
        jvmTarget = '17'
    }
    buildFeatures {
        viewBinding true
    }
    lint {
        warning 'UnusedResources'
        abortOnError false
    }
}

dependencies {
    implementation libs.core.ktx
    implementation libs.appcompat
    implementation libs.material
    implementation libs.constraintlayout
    implementation libs.navigation.fragment
    implementation libs.navigation.ui
    implementation libs.activity
    implementation libs.work.runtime
    implementation libs.libphonenumber
    testImplementation libs.junit
    androidTestImplementation libs.ext.junit
    androidTestImplementation libs.espresso.core
}